[tool.autopep8]
aggressive = 3
max_line_length = 96
ignore = "E12,E13,E201,E202,E221,E241,E261,E302,E305,E401,E402"

[tool.isort]
line_length = 96
lines_after_imports = 1
force_sort_within_sections = true
